// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//        return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//               'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//               'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCvAQtierf4wBNK1RiKn4wigoTemZ2MjHY',
//     appId: '1:879575077749:android:07afc6fe373d0a06e6393c',
//     messagingSenderId: '879575077749',
//     projectId: 'sweatsmart-f8f05',
//     storageBucket: 'sweatsmart-f8f05.appspot.com',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCvAQtierf4wBNK1RiKn4wigoTemZ2MjHY',
//     appId: '1:879575077749:android:07afc6fe373d0a06e6393c',
//     messagingSenderId: '879575077749',
//     projectId: 'sweatsmart-f8f05',
//     storageBucket: 'sweatsmart-f8f05.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCvAQtierf4wBNK1RiKn4wigoTemZ2MjHY',
//     appId: '1:879575077749:ios:2199e6e2c0dfb19fe6393c',
//     messagingSenderId: '879575077749',
//     projectId: 'sweatsmart-f8f05',
//     storageBucket: 'sweatsmart-f8f05.appspot.com',
//     iosBundleId: 'com.sweatsmart.app.sweatSmart',
//   );
//
//   static const FirebaseOptions macos =FirebaseOptions(
//     apiKey: 'AIzaSyBAiaF4C1DD9VxiiZaCukcECACGsoPvlcw',
//     appId: '1:879575077749:ios:2199e6e2c0dfb19fe6393c',
//     messagingSenderId: '879575077749',
//     projectId: 'sweatsmart-f8f05',
//     storageBucket: 'sweatsmart-f8f05.appspot.com',
//     iosBundleId: 'com.sweatsmart.app.sweatSmart',
//   );
// }
